### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by sjlleo** [TianZerL/pyanime4k#1]
**System Info:**
1. OS: Windows 10 Home Edition
2. CPU: AMD Ryzen 5 3500U with Vega 8 Graphics
3. Clean Python 3.7.6 from official download has not installed other libraries

**Things have done**:
1. Reinstall the lib pyanime4k
2. Try to run in shell but also failed

**Problem:**
```python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyanime4k
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\pyanime4k\__init__.py", line 1, in <module>
    from pyanime4k.anime4k.anime4kcpp import Anime4K
  File "C:\Python37\lib\site-packages\pyanime4k\anime4k\anime4kcpp.py", line 13, in <module>
    from . import _anime4kcpp
ImportError: DLL load failed: The specified module could not be found
```

**Comment by TianZerL** [comment]
Due to my limited energy, I only made a precompiled version of Python 3.8 in 64 bit win10, if you want to use it in python 3.7, you may need to complied it by yourself, and the Anime4KCPP of pyanime4k it out of date, now it is 3 times faster than the current version which pyanime4k are using. If you need help for compiling it, feel free to ask me.

**Comment by TianZerL** [comment]
Well, I just made  a precompiled version of Python 3.7, and updated the Anime4KCPP core to the newest. Please reinstall it, and make sure what you download is ```pyanime4k-1.0.5-cp37-none-win_amd64.whl ``` for python 3.7.

**Comment by sjlleo** [comment]
Thanks for your help! I have upgraded to Python 3.8, and testing `pyanime4k-1.0.6-cp37-none-win_amd64.whl` in Python 3.7 is also available :D 👍

**Comment by TianZerL** [comment]
I will close this issue since there is no more question.
