### ISSUE TITLE
Audio is desynced with video when upscaling 1080p -> 4K

### ISSUE THREAD

**Issue by NoPantsCrash** [TianZerL/pyanime4k#12]
Audio gets de-synced always by 8ms-12ms on the upscaled output.

**Comment by TianZerL** [comment]
For some variable frame rate videos, this problem exists. See [here](https://github.com/TianZerL/Anime4KCPP/issues/27). This is caused by built-in opencv encoder. It is recommended not to use the built-in encoder or try to specify the frame rate manually.

**Comment by NoPantsCrash** [comment]
> For some variable frame rate videos, this problem exists. See [here](https://github.com/TianZerL/Anime4KCPP/issues/27#issuecomment-719924698). This is caused by built-in opencv encoder. It is recommended not to use the built-in encoder or try to specify the frame rate manually.

How can I disable/not use the built-in opencv encoder or specify the frame rate manually using the python package?

I've installed this on Ubuntu 20.04 LTS

**Comment by TianZerL** [comment]
You need to use the low-level API

For example, specify the frame rate: 
```python
from pyanime4k import ac
import pyanime4k

parameters = ac.Parameters()
# enable HDN for ACNet
parameters.HDN = True

a = ac.AC(
    managerList=ac.ManagerList([ac.OpenCLACNetManager(pID=0, dID=0)]),
    type=ac.ProcessorType.OpenCL_ACNet
)

a.load_video(r"D:\Temp\anime4k\P1-1.m4v")

# specify output video fps here
a.set_save_video_info("output_tmp_.mp4", codec=ac.Codec.MP4V, fps = 23.976)

# start processing with progress value and time callback
a.process_with_progress()

# save video to file
a.save_video()

# merge audio and auto delete tmp file
pyanime4k.migrate_audio_streams("output_tmp.mp4",r"D:\Temp\anime4k\P1-1.m4v","output.mp4")
```
Not using the built-in opencv encoder means that you should decode every frame, treat them as a image to processing, and then encode them, instead of using `load_video` or `upscale_videos`.

**Comment by NoPantsCrash** [comment]
Alright, thank you.

**Comment by NoPantsCrash** [comment]
Sorry again.
I'm kinda confused on this, I'm getting the following error with your code snippet.
`AttributeError: module 'pyanime4k.ac' has no attribute 'ManagerList'`

**Comment by TianZerL** [comment]
Please use shell script to install pyanime4k for Linux, see [here](https://github.com/TianZerL/pyanime4k#shell-script), pip version is out of date.

**Comment by NoPantsCrash** [comment]
Understood, sorry for re-opening the issue.
