### ISSUE TITLE
Using a code formatter for the repository for easier contribution from developers

### ISSUE THREAD

**Issue by k4yt3x** [TianZerL/pyanime4k#6]
I was reading the code today and have been thinking about using a code formatter for this project, as well as some of my own projects. It will conveniently eliminate a lot of styling issues, yielding the responsibility from the coder to the formatter.

With a code formatter, the code should be more readable to all, since the code's format and style is uniform across the board. However, some might not like their code's style to be handled by a formatter.

I'm just genuinely curious what you think about code formatters (e.g. yapf or black).

**Comment by TianZerL** [comment]
I use black.

**Comment by k4yt3x** [comment]
So do I. Shall we write that into the contribution guidelines of this repo?
I'll format the repo with black as well if so.

**Comment by TianZerL** [comment]
ok.
