### ISSUE TITLE
problem: free(): invalid pointer

### ISSUE THREAD

**Issue by xtudbxk** [TianZerL/pyanime4k#8]
If I import cv2 first and import pyanime4k, then python exits with error mesage as followed:
> free(): invalide pointer

but strangely, if i import pyanime4k first and import cv2 then, everything goes well.

I just install pyanime4k accross pip and I test it on WSL2 of Win10.
This error can be avoid by import pyanime4k first, but I still open an issue for some one encounters the same issue.

**Comment by TianZerL** [comment]
Interesting, I tested it in Windows10, no mater importing pyanime4k first or cv2 first, everything goes well, but in manjaro Linux, it happened.

**Comment by TianZerL** [comment]
Well, after more testing, It will only happen in Linux which installed pyanime4k by pip. I recompiled libac.so by GCC 10 in Manjrao Linux, everything goes well.   
Linux pip version was compiled by a old version of GCC in Ubuntu 14.04, this is for making sure it can run in most of Linux distributions , but it can also lead to some compatibility problems. If it is possible, please compile libac.so by yourself for best compatibility.

**Comment by xtudbxk** [comment]
thanks~
